id: I026248B1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T14:09:41+00:00'
last_modified: '2022-06-07T20:25:03.412416+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09355
  title: ལམ་རིམ་ཆེན་མོ་མཆན་བཞི་སྦྲགས་མ། ༼ཆོས་འཕེལ་ལེགས་ལྡན།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E195:
      image_group_id: I00KG09377
      title: ''
      total_pages: 876
      order: 1
      base_file: E195.txt
    33B1:
      image_group_id: I00KG09378
      title: ''
      total_pages: 872
      order: 2
      base_file: 33B1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
