id: P004125
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09355
  title: ལམ་རིམ་ཆེན་མོ་མཆན་བཞི་སྦྲགས་མ། ༼ཆོས་འཕེལ་ལེགས་ལྡན།༽
  author: ''
  volumes:
    051591c4030a4a00a7b60eb3491f2c0e:
      image_group_id: I00KG09377
      title: ''
      volume_number: 1
      total_pages: 876
    1b6b4c5b049249e9b652fbad0c2a7b7c:
      image_group_id: I00KG09378
      title: ''
      volume_number: 2
      total_pages: 872
